name: {{cookiecutter.project_short_name}}
channels:
    - conda-forge
    - bioconda
dependencies:
    - python=3.7
    - numpy=1.15.2
    - pandas=0.23.4
    - matplotlib=3.0.0
    - seaborn=0.9.0
    - pandoc=2.3.1
    - pytest=3.8.2
    - click=7.0
    - snakemake=5.3
    - pip:
        - pytest-pythonpath # adds the root path "./" to PYTHONPATH
        - pandoc-tablenos
        - pandoc-fignos
        - pantable
