name: {{cookiecutter.project_short_name}}
channels:
    - conda-forge
    - bioconda
dependencies:
    - python=3.7
    - numpy=1.15.4
    - pandas=0.23.4
    - matplotlib=3.0.2
    - seaborn=0.9.0
    - pandoc=2.5
    - pytest=4.0.2
    - click=7.0
    - snakemake=5.4
    - pip:
        - pytest-pythonpath # adds the root path "./" to PYTHONPATH
        - pandoc-tablenos
        - pandoc-fignos
        - pantable
